### ISSUE TITLE
Locking Schedule Error

### ISSUE THREAD

**Issue by Lomet** [The-Poolz/FirewallPolicy.LockDealProvider.LockTimeOverride#14]
https://docs.google.com/document/d/1UU3129aPAsJYcmAS81K0ZFNos9WQVDhIjwVpd40DYII/edit#heading=h.1nvnn9e2o3zb

**Comment by YouStillAlive** [comment]
### **Testnet** checks

When checking the test network, two policies were created
```
0x7bdd69ea7acd516deb3941696c658f82b6ceb5b9
```
```
0xffe81592bba9b67294720d84740ccf317f77a06a
```
The settings were set:
```
Invalid = 1708880400, Valid = 1708966800
Invalid = 1708966800, Valid = 1709053200
```

### How to add a firewall?

The testnet firewall has been deployed here - https://testnet.bscscan.com/address/0x549Cdd962502111b7C28Fc43CC6BD27De0AD36B8#code

In order to finish the setup, for whichever consumer contracts you want to use the firewall/policies need to

1. Call `setFirewall('0x549Cdd962502111b7C28Fc43CC6BD27De0AD36B8')` on the **consumer (LockProvider contract)** with the account that deployed it (the deployer is the consumer admin by default)

2. Call `addPolicy(consumerAddress, sighash, policyAddress)` on the firewall contract with the same account used in (1)

#### Reproduce

1. set firewall tx: https://testnet.bscscan.com/tx/0x7541ec034660f455b4fa5393a3979b1f90f985ec07c441a8a9ea2e0c23fb5d67
2.  added the first policy tx:
https://testnet.bscscan.com/tx/0x80bbbed4791d5143d621ea67e01c2439c82c8ea5c8f765d81608dabab85f138e
added second policy tx:
https://testnet.bscscan.com/tx/0x7fcb83be613afe8c20b323a47a7bd7264dd76ea65d2056125665db102def0aac

### Results
* The first policy is expected to fail: https://testnet.bscscan.com/tx/0x3054c630cd66a5e1205647a3623f9c5396b6fc8906690049c4d4a32d8b657b72
* After valid time tx: https://testnet.bscscan.com/tx/0x9e342c3b4e3474c54c8b683ffcaca81d983f475096b4cf7a1a55b4ef0278df0e

* The second policy is expected to fail: https://testnet.bscscan.com/tx/0x89144f6039e2f4ac10c7399ce305c303727366e83f96e5dda8860f5d6fe0bbe7

**Comment by YouStillAlive** [comment]
## Mainnet policy integration
1) **set firewall tx:** https://bscscan.com/tx/0x8262c6cc209ead19f03fad5c1c18fe7d562c8e68d83f4afbde5914eb2399204b
2) Added policies:
* first policy tx:
https://bscscan.com/tx/0xe08f035d5cd4b24823492d59d7dc20054dc3267306b409840f5063fc78abea32
* second policy tx:
https://bscscan.com/tx/0xe3c8127591b035886bdfa3667c0ac952d3ddd65d4452721ab10a2590108a1f3b
* third policy tx:
https://bscscan.com/tx/0xa2735e084d20f32d099b01e501c03937f3fb00f8f645d86ceb8c557f84072213

**Comment by YouStillAlive** [comment]
https://bscscan.com/address/0x1Ea5c59fd9F4f1095DF3a894e91c3B14cA3A1bb4
